memory_limit = 256M
max_execution_time = 300
upload_max_filesize = 64M
post_max_size = 64M
display_errors = On
error_reporting = E_ALL
session.save_path = "/home/kali/COSMIC-OSINT-LAB@888/lab808/sessions"
